# Generated by Django 3.2.8 on 2021-11-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=32)),
                ('kind_name', models.CharField(max_length=32)),
                ('rank', models.CharField(max_length=8)),
                ('unit', models.CharField(max_length=8)),
            ],
        ),
    ]
